version: '3.8'
services:
  
#  config-server-service:
#    build:
#      context: ./
#      dockerfile: Dockerfile_1
#    image: config-server-service:latest
#    hostname: config-server-servic
#    restart: always
#    expose:
#      - 9010
#    ports:
#      - 9010:9010
#    container_name: config-server-service
#    networks:
#      - 'docker-network'
    
  eureka-server-service:
    build:
      context: ./
      dockerfile: Dockerfile_5
    image: eureka-server-service:latest
    hostname: eureka-server-service
    restart: always
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - 'docker-network'
    container_name: eureka-server-service
  
  gateway-service:
    build:
      context: ./
      dockerfile: Dockerfile_4
    image: gateway-service:latest
    hostname: gateway-service
    restart: always
    ports:
      - 9020:9020
    expose:
      - 9020
    networks:
      - 'docker-network'
    container_name: gateway-service
    depends_on:
      - eureka-server-service
  
  customer-service:
    build:
      context: ./
      dockerfile: Dockerfile_2
    image: customer-service:latest
    links:
      - mongoDB:mongoDB
    ports:
      - 8081:8081
    expose:
      - 8081
    container_name: customer-service
    hostname: customer-service
    restart: always
    networks:
      - 'docker-network'
    depends_on:
      - mongoDB
      - eureka-server-service

      
  transaction-service:
    build:
      context: ./
      dockerfile: Dockerfile_3
    image: transaction-service:latest
    links:
      - mongoDB:mongoDB
    ports:
      - 8082:8082
    expose:
      - 8082
    container_name: transaction-service
    hostname: transaction-service
    restart: always
    networks:
      - 'docker-network'
    depends_on:
      - mongoDB
      - eureka-server-service
  
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    hostname: mongoDB
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - 'docker-network'

networks:
  docker-network: